spring:
    profiles:
        active: native
    application:
        name: configuration-service
    cloud:
        config:
            server:
                native:
                    search-locations: classpath:/configurations
server:
    port: 8890
    
