application:
    kafka:
        user:
            user-approval-group: user-approval-group-1
    security:
        allow:
            specific: /api/${application.version}/authentication/login, api/${application.version}/authentication/isValid
spring:
    datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:mem:authentication-service
        username: root
        password: <DATABASE_PASSWORD>
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
server:
    port: 8080