application:
    kafka:
        user:
            user-approval-group: user-approval-group-1
    security:
        allow:
            specific: /api/${application.version}/authentication/register, /api/${application.version}/authentication/login, /api/${application.version}/authentication/isValid
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/authentication
        username: root
        password: Surya@123
    jpa:
        database-platform: org.hibernate.dialect.MySQLDialect
        hibernate:
            ddl-auto: create
server:
    port: 8080