server:
    port: 8087
application:
    kafka:
        consumer:
            order-consumer: order-consumer-cart-group-1
spring:
    data:
        mongodb:
            host: localhost
            port: 27017
            database: ${spring.application.name}
            authentication-database: admin
