server:
    port: 8090
application:
    kafka:
        consumer:
            customer-update-group: customer-update-notification-group-1
            seller-update-group: seller-update-notification-group-1
            employee-update-group: employee-update-notification-group-1
            user-update-group: user-update-notification-group-1
            order-group: order-notification-group-1
            approval-notification-group: approval-notification-group-1
            category-group: category-notification-group-1
            product-group: product-notification-group-1
            variant-group: variant-notification-group-1
            inventory-group: inventory-notification-group-1
            payment-group: payment-notification-group-1
            inventory-update-group: inventory-update-notification-group-1
            tracking-group: tracking-notification-group-1
spring:
    data:
        mongodb:
            host: localhost
            port: 27017
            database: ${spring.application.name}
            authentication-database: admin
    mail:
        host: smtp.gmail.com
        port: 587
        username: <GMAIL>
        password: <GOOGLE_APP_PASSWORD>
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true