application:
    kafka:
        consumer:
            payment-group: payment-order-group-1
            inventory-approval-group: inventory-approval-group-1
            tracking-group: tracking-group-1
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3308/order-inventory
        username: root
        password: Surya@123
    jpa:
        database-platform: org.hibernate.dialect.MySQLDialect
        hibernate:
            ddl-auto: create
server:
    port: 8088