server:
    port: 8083
application:
    kafka:
        consumer:
            product-group: product-consumer-group
            variant-group: variant-consumer-group
spring:
    data:
        mongodb:
            host: localhost
            port: 27017
            database: product-management-service
            authentication-database: admin
        redis:
            host: localhost
            port: 6379
    cache:
        redis:
            time-to-live: 300