server:
    port: 8091
application:
    kafka:
        consumer:
            order-tracking-group: order-tracking-group-1
spring:
    data:
        mongodb:
            host: localhost
            port: 27017
            database: tracking-management-service
            authentication-database: admin