application:
    kafka:
        consumer:
            user:
                user-approval-group: user-approval-group-2
    security:
        allow:
            specific: /api/${application.version}/users/customers/register, /api/${application.version}/users/employees/register, /api/${application.version}/users/sellers/register
server:
    port: 8081
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3307/user-management
        username: root
        password: <DATABASE_PASSWORD>
    jpa:
        database-platform: org.hibernate.dialect.MySQLDialect
        hibernate:
            ddl-auto: create